#!/usr/bin/env sh

# Small wrapper for helm downloader
# Called with args: certFile keyFile caFile full-URL

set -e

# Resolve HELM_BIN to an absolute path
HELM_BIN=$(readlink -f "$(command -v "$HELM_BIN")")
export HELM_BIN

# cd to helm-git plugin folder
cd "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)" >&2

# shellcheck disable=SC1091
. "./helm-git-plugin.sh"

main "$1" "$2" "$3" "$4"
