name: "helm-git"
version: "0.17.0"
description: |-
  Get non-packaged Charts directly from Git.
downloaders:
- command: "/usr/bin/env sh helm-git"
  protocols:
    - "git+file"
    - "git+ssh"
    - "git+https"
    - "git+http"
