name: "helm-git"
version: "1.1.0"
description: |-
  Get non-packaged Charts directly from Git.
downloaders:
- command: "helm-git"
  protocols:
    - "git+file"
    - "git+ssh"
    - "git+https"
    - "git+http"
