name: pull-request

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
